### PR TITLE
AC button feature added.

### PR DESCRIPTION
**Pull request by VedantpD**
AC button feature added and change the primary color from purple to black.

### CODE REVIEW

**Comment by VedantpD** [comment]
@Jacinth-Mahanta Please review and merge the PR also add the hactoberfest-accepted label.

**Comment by VedantpD** [comment]
@Jacinth-Mahanta Bro it says the repo is not participating in the hactoberfest.

**Comment by Jacinth-Mahanta** [comment]
> @Jacinth-Mahanta Bro it says the repo is not participating in the hactoberfest.

Check now.

**Comment by VedantpD** [comment]
@Jacinth-Mahanta yep it's added now. Thanks

**Pull request merged**
